name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  validate-node:
    name: 'Validate'
    uses: curium-rocks/flows/.github/workflows/node-ts.yml@main
    permissions:
      contents: read
      actions: read
      security-events: write
    with:
      continue-on-prod-vulns: false
      node_versions: '{"node-version": ["16.x","18.x","20.x"]}'
    secrets:
      SONARQUBE_KEY: ${{ secrets.SONARQUBE_KEY }}
  build-image:
    name: 'Build container image'
    uses: curium-rocks/flows/.github/workflows/oci-build-image.yml@main
    needs: validate-node
    permissions:
      contents: read
      packages: write
      security-events: write
      id-token: write
    with:
      registry: ghcr.io/bryopsida
      image_name: nestjs-starter
      push_in_pr: true
  deploy-container:
    needs: build-image
    name: 'Helm'
    uses: curium-rocks/flows/.github/workflows/helm-qa.yml@main
    with:
      charts_dir: 'charts'
      helm_extra_sets: '--set image.tag=${{ needs.build-image.outputs.build_tag }}'
      ct_extra_args: '--all'
